# Generated by Django 5.2.1 on 2025-06-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(choices=[('EUROPE', 'Europe'), ('BURUNDI', 'Burundi')], max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('currency', 'location'), name='unique_stock_per_currency_location')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('custom_exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='mta.stock')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mta.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('to_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defined_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency', 'created_at')},
            },
        ),
    ]
