# Generated by Django 5.2.1 on 2025-06-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0002_stock_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_phone', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('LUMICASH', 'Lumicash'), ('ECOCASH', 'Ecocash')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sent_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('received_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('COMPLETED', 'Complété'), ('CANCELED', 'Annulé')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_transfers', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
