# Generated by Django 5.2.1 on 2025-06-13 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mta', '0003_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agent_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('declaring_agent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('manager_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('config_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mta.commissionconfig')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mta.transfer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('agent_share__gte', 0), ('agent_share__lte', 100)), name='valid_agent_share'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.UniqueConstraint(fields=('manager', 'min_amount', 'max_amount', 'currency', 'active'), name='unique_config_range'),
        ),
    ]
