# Generated by Django 5.2.3 on 2025-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant maximum')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de commission (%)')),
                ('agent_share', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Part agent (%)')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Configuration de Commission',
                'verbose_name_plural': 'Configurations de Commission',
                'ordering': ['currency', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='CommissionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Commission totale')),
                ('declaring_agent_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant agent')),
                ('manager_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant manager')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Distribution de Commission',
                'verbose_name_plural': 'Distributions de Commission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=100, verbose_name='Nom du bénéficiaire')),
                ('beneficiary_phone', models.CharField(max_length=20, verbose_name='Téléphone du bénéficiaire')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('LUMICASH', 'Lumicash'), ('ECOCASH', 'Ecocash')], max_length=50, verbose_name='Méthode de retrait')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('sent_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3, verbose_name='Devise envoyée')),
                ('received_currency', models.CharField(choices=[('EUR', 'Euro'), ('BIF', 'Franc Burundais'), ('USD', 'Dollars')], max_length=3, verbose_name='Devise reçue')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('COMPLETED', 'Complété'), ('CANCELED', 'Annulé')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('validation_comment', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Exécuté le')),
                ('execution_comment', models.TextField(blank=True, null=True, verbose_name="Commentaire d'exécution")),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
