# Generated by Django 5.2.3 on 2025-06-15 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionconfig',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='commissiondistribution',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_earnings', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='commissiondistribution',
            name='config_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfers.commissionconfig', verbose_name='Configuration utilisée'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='commissiondistribution',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='transfers.transfer', verbose_name='Transfer'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('agent_share__gte', 0), ('agent_share__lte', 100)), name='valid_agent_share'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='valid_commission_rate'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__lte', models.F('max_amount'))), name='valid_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('manager', 'min_amount', 'max_amount', 'currency'), name='unique_active_config_range'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', '-created_at'], name='transfers_t_status_848455_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['agent', '-created_at'], name='transfers_t_agent_i_cf672f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['validated_by', '-created_at'], name='transfers_t_validat_f5f418_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiondistribution',
            index=models.Index(fields=['agent', '-created_at'], name='transfers_c_agent_i_871603_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiondistribution',
            index=models.Index(fields=['-created_at'], name='transfers_c_created_b12c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiondistribution',
            index=models.Index(fields=['transfer'], name='transfers_c_transfe_af8082_idx'),
        ),
    ]
