# Generated by Django 5.2.3 on 2025-07-01 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commissionconfig',
            name='valid_commission_rate',
        ),
        migrations.AlterField(
            model_name='commissionconfig',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de commission'),
        ),
        migrations.AddConstraint(
            model_name='commissionconfig',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0)), name='valid_commission_rate'),
        ),
    ]
